### ISSUE TITLE
Pool without key

### ISSUE THREAD

**Issue by AL333Z** [typelevel/keypool#254]
Hi,
is it worth it to introduce a specialized pool without keys?

This is a sample that is sticking `Unit` as the key:

```
// def site
val pool = KeyPool.Builder[IO, Unit, MyThing]{ _ =>
  Resource.make(???)(???)
}

// use site
pool.take(()).use { myThing =>
  ???
}
```

This is how it would be:

```
// def site
val pool = Pool.Builder[IO, MyThing]{
  Resource.make(???)(???)
}

// use site
pool.take.use { myThing =>
  ???
}
```

Not sure it's worth it, but maybe this is a not so uncommon scenario.
Also, in the implementation, we may do some inlining (e.g. no need for a Map-like structure).
I'd be available to work on this.

**Comment by rossabaker** [comment]
It goes against the name of the project, but I think it's a good use case.  Because I'm an old Java fart, I consider commons-pool2 to be an inspiration, and that has both a keyed and unkeyed pool.  I'm in favor of this.

I wonder whether an inlined implementation is worthwhile.  It would duplicate a lot of logic, and the runtime cost of the map-like structure should be insignificant on objects we care enough to pool.  You could make a substantially simpler implementation without the map, but it would also be less tested than delegating to a unit-keyed one.  I don't have a strong opinion on what's right here.

**Comment by AL333Z** [comment]
You basically summarized all my doubts, starting from the name of the lib to the inlining cost/benefit.
I think I can provide a PR soon, let's iterate once I have something ready.
